language: python
cache:
  - apt
  - pip
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.6-dev"
install: "make"
script:
  - make ci
before_install:
  - sudo apt-get install -y libpython-dev
  - sudo apt-get install -y libyaml-dev
  - sudo apt-get install -y python-dev
  - sudo apt-get install -y python-pip
  - sudo apt-get install -y python-software-properties
  - sudo apt-get install -y software-properties-common
sudo: required
after_success:
  coveralls
notifications:
  slack: watchcloud:rNoT5kJJakPqwLSKuev6oa4C
