language: python
cache:
  - apt
  - pip
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
  - "nightly"
install:
  - pip install --upgrade pipenv
  - pipenv install --dev --ignore-pipfile
before_script: flake8
script: pipenv run pytest --cov-report term-missing --cov=pytube
sudo: required
after_success:
  coveralls
notifications:
  slack: watchcloud:rNoT5kJJakPqwLSKuev6oa4C
