language: python
cache:
  - apt
  - pip
python:
  - "3.5"
  - "3.6"
  - "3.7"
install: "make"
script:
  - make ci
before_install:
  - pip install pipenv flake8 --upgrade
sudo: false
after_success:
  coveralls
notifications:
#  slack: watchcloud:rNoT5kJJakPqwLSKuev6oa4C
